- name: Download a tagged Drush release
  get_url: url=https://github.com/drush-ops/drush/releases/download/{{ drush.version }}/drush.phar
           dest={{ drush.path }} mode=0755
  when: drush.version != 'master'

- name: Download Drush master
  get_url: url=http://files.drush.org/drush.phar
           dest={{ drush.path }} mode=0755
  when: drush.version == 'master'
