---
- name: check if the configured php7 version is already installed
  shell: "ls {{ php7-src.base_path }}|grep {{ php7-src.version }}|wc -l"
  register: php7_install_status

- set_fact: php7_installed="{{ php7_install_status.rc == 1 }}"

- name: install all needed packages for compiling php7 from source
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: php7-src.packages_dev
  when: not php7_installed

- name: symlink the gmp library header
  file: src=/usr/include/x86_64-linux-gnu/gmp.h dest=/usr/include/gmp.h state=link
  when: not php7_installed

- name: symlink the libc client library
  file: src=/usr/lib/libc-client.a dest=/usr/lib/x86_64-linux-gnu/libc-client.a state=link
  when: not php7_installed

- name: clone php7 repository
  git: repo=https://git.php.net/repository/php-src.git
       dest=/tmp/php-src/{{ php7-src.version }}
       version={{ php7-src.version }}
       depth=1
  when: not php7_installed

- name: build configuration for the compiler for php7
  command: ./buildconf --force chdir=/tmp/php-src/{{ php7-src.version }}
  when: not php7_installed

- name: configure the compiler for php7
  command: ./configure \
        --disable-rpath \
        --enable-bcmath \
        --enable-calendar \
        --enable-exif \
        --enable-fpm \
        --enable-ftp \
        --enable-gd-jis-conv \
        --enable-gd-native-ttf \
        --enable-inline-optimization \
        --enable-mbregex \
        --enable-mbstring \
        --enable-opcache \
        --enable-opcache-file \
        --enable-pcntl \
        --enable-soap \
        --enable-sysvmsg \
        --enable-sysvsem \
        --enable-sysvshm \
        --enable-wddx \
        --enable-zip \
        --prefix={{ php7-src.prefix }} \
        --with-bz2=/usr \
        --with-config-file-path={{ php7-src.config_file.path }} \
        --with-curl \
        --with-fpm-group={{ php7-src.fpm.group }} \
        --with-fpm-user={{ php7-src.fpm.user }} \
        --with-freetype-dir=/usr \
        --with-gd \
        --with-gettext=/usr \
        --with-gmp \
        --with-iconv \
        --with-imap \
        --with-imap-ssl \
        --with-jpeg-dir=/usr \
        --with-kerberos \
        --with-libdir=/lib/x86_64-linux-gnu \
        --with-libxml-dir=/usr \
        --with-mcrypt \
        --with-mhash \
        --with-mysqli=/usr/bin/mysql_config \
        --with-openssl \
        --with-pcre-regex \
        --with-pdo-mysql=/usr \
        --with-pdo-pgsql \
        --with-pgsql \
        --with-png-dir=/usr \
        --with-pspell \
        --with-xmlrpc \
        --with-xpm-dir=/usr \
        --with-xsl \
        --with-zlib-dir \
        --with-zlib=/usr
    chdir=/tmp/php-src/{{ php7-src.version }}
  when: not php7_installed

- name: compile php7
  command: make chdir=/tmp/php-src/{{ php7-src.version }}
  when: not php7_installed

- name: install php7
  command: make install chdir=/tmp/php-src/{{ php7-src.version }}
  when: not php7_installed

- name: symlink the installation folder
  file: src={{ php7-src.prefix }} dest={{ php7-src.base_path }}/php7 state=link
  when: not php7_installed

- name: ensure php config directory exists
  file:
    path: "{{ php7-src.config_file.path }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
  when: not php7_installed

- name: install php.ini file
  sudo: yes
  template: src=php.ini.tpl dest={{ php7-src.config_file.path }}
  notify: restart apache
  when: not php7_installed

- name: install php-fpm.conf file
  sudo: yes
  template: src=php-fpm.conf.tpl dest={{ php7-src.prefix }}/etc/php-fpm.conf
  notify: restart apache
  when: not php7_installed

- name: install System V init script
  sudo: yes
  template: src=init.d.tpl dest=/etc/init.d/php7-fpm
  notify: restart apache
  when: not php7_installed

- name: install init script
  sudo: yes
  template: src=init.tpl dest=/etc/init/php7-fpm.conf
  notify: restart apache
  when: not php7_installed

- name: install checkconf script
  sudo: yes
  template: src=php7-fpm-checkconf.tpl dest=/usr/local/lib/php7-fpm-checkconf
  notify: restart apache
  when: not php7_installed
