---
server:
    install: '1'
    packages: [vim, git, fail2ban, htop, iotop, imagemagick, nodejs, npm]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.88.88, memory: '1024', sharedfolder: ../website, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /var/www/milan2016.drupaldays.loc/web
    servername: milan2016.drupaldays.loc
    user: vagrant
    group: vagrant
xdebug:
    install: '1'
composer:
    install: '1'
    install_dir: /usr/local/bin
    path: /usr/local/bin/composer
    home_path: '/home/vagrant/.composer'
    home_path_owner: vagrant
    home_path_group: vagrant
    skip_dev_deps: no
app:
    drupal_core_path: /var/www/milan2016.drupaldays.loc
    env: local

security_ssh_password_authentication: yes
security_ssh_permit_root_login: no
