---
- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ php7.ppa }}

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install php
  sudo: yes
  apt: pkg=php state=latest

# - name: Install php-fpm
#   sudo: yes
#   apt: pkg=php-fpm state=latest

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: php7.packages
  when: php7.packages is defined
  notify: restart apache
