---
- name: Check if site is already installed.
  shell: "{{ drush.path }} status bootstrap"
  args:
    chdir: "{{ app.drupal_core_path }}/web"
  failed_when: false
  changed_when: false
  become: no
  register: drupal_site_installed

- name: Ensure composer directory can be written
  file:
    path: "{{ composer.home_path }}"
    state: directory
    owner: "{{ composer.home_path_owner }}"
    group: "{{ composer.home_path_group }}"
    mode: 0755

- name: Ensure drupal files directory can be written
  file:
    path: "{{ app.drupal_core_path }}/sites/default/files"
    state: directory
    mode: 0755

- name: Run Composer install
  composer: command=install
            working_dir={{ app.drupal_core_path }}
            prefer_dist=yes
            no_dev={{ composer.skip_dev_deps }}
  when: "'Successful' not in drupal_site_installed.stdout"

- name: Build the site using robo
  command: >
    ./vendor/bin/robo build:local
    chdir={{ app.drupal_core_path }}
  sudo: yes
  when: "'Successful' not in drupal_site_installed.stdout"
