---
- hosts: all
  sudo: true
  vars_files:
    - vars/common.yml
    - vars/staging_vault.yml
    - vars/staging.yml
  roles:
    - {
        role: server,
        tags: [ 'server' ]
      }
    - {
        role: geerlingguy.firewall,
        tags: [ 'server' ]
      }
    - {
        role: geerlingguy.security,
        tags: [ 'server' ]
      }
    - {
        role: mivok0.users,
        tags: [ 'users' ]
      }
    - {
        role: geerlingguy.postfix,
        tags: [ 'emailing' ]
      }
    - {
        role: apache,
        tags: [ 'apache' ]
      }
    - {
        role: mysql,
        tags: [ 'mysql' ]
      }
    - {
        role: php7,
        tags: [ 'php' ]
      }
    - {
        role: composer,
        tags: [ 'php-tools' ]
      }
    - {
        role: app,
        tags: [ 'app' ]
      }
