---
- hosts: all
  sudo: true
  vars_files:
    - vars/vagrant.yml
  roles:
    - {
        role: vagrant_local,
        tags: [ 'vagrant' ]
      }
    - {
        role: server,
        tags: [ 'server' ]
      }
    - {
        role: geerlingguy.firewall,
        tags: [ 'server' ]
      }
    - {
        role: geerlingguy.postfix,
        tags: [ 'emailing' ]
      }
    - {
        role: apache,
        tags: [ 'apache' ]
      }
    - {
        role: mysql,
        tags: [ 'mysql' ]
      }
    - {
        role: php7,
        tags: [ 'php' ]
      }
    - {
        role: composer,
        tags: [ 'php-tools' ]
      }
    - {
        role: drush,
        tags: [ 'php-tools' ]
      }
    - {
        role: app,
        tags: [ 'app' ]
      }
